theme: jekyll-theme-minimal
title: Matthew J. Smith, PhD
description: Postdoctoral Research Fellow at the London School of Hygiene & Tropical Medicine. <br/> <a href="https://orcid.org/0000-0002-8502-0056", target="_blank"> [ORCID] </a> <a href="http://twitter.com/mjtsmith/", target="_blank"> [Twitter] </a> <br/><br/>
#logo: /img/ae.jpg
